version: 2

run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - govet        # Vet examines Go source code and reports suspicious constructs
    - errcheck     # Errcheck is a program for checking for unchecked errors in Go code
    - staticcheck  # Staticcheck is a go vet on steroids, applying a ton of static analysis checks
    - ineffassign  # Detects when assignments to existing variables are not used

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
